title: Accountable Bookworm Book Keeping
email: info@accountablebookworm.com.au
description: >
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.accountablebookworm.com.au"
markdown: kramdown
